'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let catalog,kind='',matches=[],page=0,selected=-1,request=0,bodyRequest=0;const cache=new Map(),size=15;const labels={commentary:'经文注释',sermon:'讲章',theology:'神学书籍'};
async function load(path){if(cache.has(path))return cache.get(path);const p=(async()=>{const r=await fetch(path);if(!r.ok)throw Error('资料读取失败，请稍后重试。');const bytes=new Uint8Array(await r.arrayBuffer());if(bytes[0]===31&&bytes[1]===139){if(!('DecompressionStream' in window))throw Error('请使用新版 Safari、Chrome、Edge 或 Firefox 打开。');return JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text())}return JSON.parse(new TextDecoder().decode(bytes))})();cache.set(path,p);try{return await p}catch(e){cache.delete(path);throw e}}
function name(author){return catalog.aliases[author]||author||'作者未标注'}
function ref(r){const b=catalog.books.find(b=>b.book===r[0]);return (b?.chinese||r[0])+' '+r[1]+(r[2]>0?':'+r[2]+(r[3]>r[2]?'–'+r[3]:''):'')}
function terms(q){const stop=new Set(catalog.stopwords),words=(q.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(x=>x.length>1&&!stop.has(x));for(const z of q.match(/[\u3400-\u9fff]+/g)||[]){if(z.length===1)words.push(z);else for(let i=0;i<z.length-1;i++)words.push(z.slice(i,i+2))}return [...new Set(words)]}
function decode(s){if(!s)return new Set();let last=0;return new Set(s.split('.').map(x=>last+=parseInt(x,36)))}
function selectedRefs(d){const book=$('book').value,ch=Number($('chapter').value),v=Number($('verse').value);return d[5].filter(r=>(!book||r[0]===book)&&(!ch||r[1]===ch)&&(!v||(r[2]>0&&r[2]<=v&&r[3]>=v)))}
function evidence(d){return d[7]==='legacy-unreviewed'?'旧版样本 · 待复核':d[3]==='theology'?'正文引用 · 自动提取':d[3]==='sermon'?'主讲经文 · 上游标注':'释义范围 · 上游标注'}
function visibleTitle(d){return d[3]==='commentary'?d[1].replace(/ · [a-z0-9]+ \d+:.+$/,''):d[1]}
function rank(d){const refs=selectedRefs(d),v=Number($('verse').value);let n=d[3]==='commentary'?0:d[3]==='sermon'?100000:200000;if(d[7]==='legacy-unreviewed')n+=300000;if(v&&refs.length)n+=Math.min(...refs.map(r=>r[3]-r[2]));return n}
async function query(){
 if(!catalog)return;const token=++request;page=0;$('status').textContent='正在检索……';
 const q=$('q').value.trim(),book=$('book').value,ch=Number($('chapter').value),verse=Number($('verse').value),author=$('author').value,trad=$('tradition').value,zh=$('language').value;
 if((ch||verse)&&!book){$('status').textContent='请先选择书卷，再指定章或节。';return}
 if(verse&&!ch){$('status').textContent='请先填写章，再指定节。';return}
 if(ch&&(!Number.isInteger(ch)||ch<1||!catalog.chapter_limits[book]?.[ch])){$('status').textContent='所选书卷没有这一章，请检查章号。';return}
 if(verse&&(!Number.isInteger(verse)||verse<1||verse>catalog.chapter_limits[book]?.[ch])){$('status').textContent='节号超出本章范围，请检查。';return}
 try{let accepted=null;const words=terms(q);if(q&&!words.length){$('status').textContent='请输入更具体的关键词，当前仅包含常见词。';return}
 if(words.length){const buckets=[...new Set(words.map(w=>[...w].reduce((a,c)=>a+c.codePointAt(0),0)%128))],index=new Map(await Promise.all(buckets.map(async b=>[b,await load('data/index/'+b+'.gz')]))),sets=words.map(w=>decode(index.get([...w].reduce((a,c)=>a+c.codePointAt(0),0)%128)[w])).sort((a,b)=>a.size-b.size);accepted=sets[0];for(const st of sets.slice(1))accepted=new Set([...accepted].filter(x=>st.has(x)))}
 if(token!==request)return;matches=[];
 catalog.documents.forEach((d,i)=>{if(accepted&&!accepted.has(i))return;if(kind&&d[3]!==kind)return;if(author&&d[2]!==author)return;if(trad&&!catalog.works[d[0]].tradition.includes(trad))return;if(zh&&!d[4])return;
 if(book){if(!selectedRefs(d).length)return;if($('association').value==='direct'&&(d[3]==='theology'||d[7]==='legacy-unreviewed'))return}matches.push(i)});
 matches.sort((a,b)=>rank(catalog.documents[a])-rank(catalog.documents[b])||a-b);
 const counts={commentary:0,sermon:0,theology:0};matches.forEach(i=>counts[catalog.documents[i][3]]++);
 $('status').textContent='找到 '+matches.length.toLocaleString()+' 条 · 注释 '+counts.commentary+' / 讲章 '+counts.sermon+' / 书籍 '+counts.theology;
 render();const p=new URLSearchParams();for(const id of ['q','book','chapter','verse','author','tradition','language','association'])if($(id).value)p.set(id,$(id).value);if(kind)p.set('kind',kind);history.replaceState(null,'',location.pathname+(p.size?'?'+p.toString():''));
 if(!matches.includes(selected)){++bodyRequest;selected=-1;if(matches.length)await read(matches[0]);else $('reader').innerHTML='<div class="empty"><span class="eyebrow">暂无匹配资料</span><h2>换一个查考方向。</h2><p>可以清空作者或译文筛选，也可以选择“同时查看引用线索”。英文正文请用英文关键词。</p></div>'}
 }catch(e){if(token===request)$('status').textContent=e.message}
}
function render(){const current=matches.slice(page*size,(page+1)*size);$('list').innerHTML=current.length?current.map(i=>{const d=catalog.documents[i],target=$('book').value?selectedRefs(d):d[5],display=target.slice(0,2).map(ref).join('；');return '<button class="result '+(selected===i?'selected':'')+'" data-id="'+i+'" aria-pressed="'+(selected===i)+'"><span class="badge '+(d[3]==='theology'?'citation':'')+'">'+esc(labels[d[3]]||d[3])+'</span>'+(d[4]?' <span class="badge">有中文</span>':'')+'<h3>'+esc(visibleTitle(d))+'</h3><p>'+esc(name(d[2]))+'</p><p class="matchref">'+esc(display||'未标注经文范围')+(target.length>2?' 等 '+target.length+' 处':'')+'</p><span class="relationlabel">'+esc(evidence(d))+'</span></button>'}).join(''):'<p class="error">没有找到资料。可放宽筛选或查看引用线索。</p>';$('prev').disabled=page===0;$('next').disabled=(page+1)*size>=matches.length;$('page').textContent=matches.length?(page+1)+' / '+Math.ceil(matches.length/size):'0 / 0';document.querySelectorAll('.result').forEach(b=>b.onclick=()=>read(Number(b.dataset.id)))}
async function read(i){const token=++bodyRequest;selected=i;render();$('reader').innerHTML='<p role="status">正在加载完整正文……</p>';try{const d=catalog.documents[i],w=catalog.works[d[0]],chunk=await load('data/text/'+Math.floor(i/catalog.chunk_size)+'.gz'),b=chunk[i%catalog.chunk_size];if(token!==bodyRequest)return;let url='';try{const u=new URL(w.source_url);if(['https:','http:'].includes(u.protocol))url=u.href}catch{};
 const matched=$('book').value?selectedRefs(d):d[5];
 $('reader').innerHTML='<span class="badge">'+esc(labels[d[3]])+'</span><h1>'+esc(visibleTitle(d))+'</h1><div class="meta">'+esc(name(d[2]))+' · '+esc(w.title)+'</div><div class="matchnote"><strong>'+esc(evidence(d))+'</strong><br>'+esc(matched.map(ref).join('；')||'未标注经文范围')+(d[3]==='theology'?'<br>该段落引用了经文，不能据此认定它是在解释该节。':d[3]==='sermon'?'<br>来源标注为主讲经文，尚未逐篇人工校订。':'<br>范围按来源结构标注；已检查编号和标题，正文尚未逐篇人工校订。')+'</div><nav aria-label="阅读方式"><button id="original">原文</button>'+(b[1]?'<button id="chinese">中文译文</button><button id="parallel">双语并读</button>':'')+'<span class="fontcontrols"><button id="smaller" aria-label="缩小字号">A−</button><button id="larger" aria-label="放大字号">A＋</button><button id="copy">复制正文</button></span></nav><div id="translationNotice"></div><div id="body" class="bodytext"></div><details><summary>全部经文、出处与核验状态</summary><p>资料关联的全部经文：'+esc(d[5].map(ref).join('；')||'未标注')+'</p><p>原著版权及整理数据许可：'+esc(w.rights||'待复核')+'</p><p>版本：'+esc(w.edition||'未标注')+'</p><p>译文状态：'+esc(b[2]||'未翻译')+'</p><p>来源文件：'+esc(b[4])+'</p><p>核验：数字范围检查与元数据检查。经文引用关系仍需结合原文判断。</p>'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">查阅原始来源 ↗</a>':'')+'</details>';
 let view='original',font=19;const show=mode=>{view=mode;$('body').classList.toggle('parallel',mode==='parallel');if(mode==='parallel')$('body').innerHTML='<section><h2>原文</h2>'+esc(b[0])+'</section><section><h2>机器译文</h2>'+esc(b[1])+'</section>';else $('body').textContent=mode==='chinese'?b[1]:b[0];$('translationNotice').innerHTML=mode!=='original'?'<p class="notice">机器译文 · 未经人工校订。请对照原文核对神学术语、人名与论证。</p>':'';for(const id of ['original','chinese','parallel'])$(id)?.classList.toggle('active',id===mode)};
 $('original').onclick=()=>show('original');if(b[1]){$('chinese').onclick=()=>show('chinese');$('parallel').onclick=()=>show('parallel')}
 $('smaller').onclick=()=>{$('body').style.fontSize=(font=Math.max(15,font-1))+'px'};$('larger').onclick=()=>{$('body').style.fontSize=(font=Math.min(26,font+1))+'px'};
 $('copy').onclick=async()=>{try{await navigator.clipboard.writeText(name(d[2])+' · '+w.title+'\n'+matched.map(ref).join('；')+'\n\n'+(view==='chinese'?b[1]:view==='parallel'?b[0]+'\n\n[机器译文·未校订]\n'+b[1]:b[0]));$('copy').textContent='已复制'}catch{$('copy').textContent='复制失败，请选择正文复制'}};
 show('original');if(innerWidth<700)$('reader').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){if(token===bodyRequest)$('reader').innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
$('search').onsubmit=e=>{e.preventDefault();query()};for(const id of ['author','tradition','language','association'])$(id).onchange=query;$('book').onchange=()=>{$('chapter').value='';$('verse').value='';query()};document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;if(kind==='theology')$('association').value='all';document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));query()});$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};$('reset').onclick=()=>{for(const id of ['q','book','chapter','verse','author','tradition','language'])$(id).value='';kind='';$('association').value='direct';document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',!x.dataset.kind));query()};$('example').onclick=()=>{$('book').value='john';$('chapter').value=3;$('verse').value=16;query()};$('about').onclick=()=>$('details').showModal();document.querySelector('.close').onclick=()=>$('details').close();
(async()=>{try{catalog=await load('data/catalog.gz?v=2');$('book').innerHTML='<option value="">全部书卷</option>'+catalog.books.map(b=>'<option value="'+esc(b.book)+'">'+esc(b.chinese)+'</option>').join('');const authors=[...new Set(catalog.documents.map(d=>d[2]))].sort((a,b)=>name(a).localeCompare(name(b),'zh-CN'));$('author').innerHTML='<option value="">全部作者</option>'+authors.map(a=>'<option value="'+esc(a)+'">'+esc(name(a))+'</option>').join('');const traditions=[...new Set(catalog.works.flatMap(w=>w.tradition))].sort();$('tradition').innerHTML='<option value="">全部传统</option>'+traditions.map(t=>'<option value="'+esc(t)+'">'+esc(({reformed:'改革宗',baptist:'浸信会',methodist:'循道宗',wesleyan:'卫斯理传统',lutheran:'路德宗',anglican:'圣公会',presbyterian:'长老会',evangelical:'福音派',arminian:'阿民念传统',patristic:'早期教父',catholic:'天主教',puritan:'清教徒',calvinist:'加尔文主义', 'calvinist-methodist':'加尔文派循道宗',confessional:'信条传统',congregationalist:'公理宗','dutch-reformed':'荷兰改革宗',ecumenical:'跨宗派','free-church':'自由教会',fundamentalist:'基要派',holiness:'圣洁传统',jansenist:'詹森派','non-denominational':'独立教会',nonconformist:'非国教',orthodox:'东正教','particular-baptist':'特定浸信会',quaker:'贵格会',revivalist:'复兴传统'})[t]||t)+'</option>').join('');const p=new URLSearchParams(location.search);if(p.size){for(const id of ['q','book','chapter','verse','author','tradition','language','association'])if(p.has(id))$(id).value=p.get(id);kind=p.get('kind')||'';document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('active',x.dataset.kind===kind))}else{$('book').value='john';$('chapter').value=3;$('verse').value=16}await query()}catch(e){$('status').textContent=e.message}})();
